-- Your SQL goes herE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS (
  id UUID DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,
  passwd VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)