version: '3.6'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: slinger
      POSTGRES_PASSWORD: dev
    networks:
      - slinger
    ports:
      - 5432:5432
    restart: always
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - slinger
    ports:
      - 6379:6379
    restart: always

networks:
  slinger: